apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wp
  name: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wp
    spec:
      containers:
      - image: docker.io/wordpress
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              key: myhost
              name: wpsecret
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              key: myuser
              name: wpsecret
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mypass
              name: wpsecret
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              key: myname
              name: wpsecret
